import type { Metadata } from "next";
import {  Exo_2, Kanit, Open_Sans } from "next/font/google";
import "./globals.css";
import StarknetProvider from "@/context/starknet-provider"; 
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";




const exo2 = Exo_2({
  variable: "--font-exo-2",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
});;


const kanit = Kanit({ 
  variable: "--font-kanit", 
  weight: "800",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${openSans.variable} ${exo2.variable} ${kanit.variable} flex flex-col h-screen antialiased`}
      >
        <StarknetProvider>
          {children}
          <Toaster />
        </StarknetProvider>
        <Footer />
      </body>
    </html>
  );
}
